import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css69=fs.readFileSync(new URL('../src/v10469.css',import.meta.url),'utf8');
const css70=fs.readFileSync(new URL('../src/v10470.css',import.meta.url),'utf8');
assert.match(main,/const bulkDialogRef=useRef\(null\)/);
assert.match(main,/body\.style\.overflow='hidden'/);
assert.match(main,/root\.style\.overflow='hidden'/);
assert.match(main,/addEventListener\('wheel',onWheel,\{passive:false\}\)/);
assert.match(main,/const rightPanel=origin\.closest\('\.parts-v50-bulk-select'\)/,'coluna direita precisa ser detectada explicitamente');
assert.match(main,/const rightList=dialog\.querySelector\('\.parts-v49-bulk-list'\)/,'lista de aparelhos precisa ser alvo explicito do wheel');
assert.match(main,/if\(rightPanel\)\{\s*event\.preventDefault\(\);\s*if\(scrollElement\(rightList,event\.deltaY\)\)return/,'wheel da coluna direita deve rolar a lista de aparelhos manualmente');
assert.match(main,/removeEventListener\('wheel',onWheel\)/);
assert.match(css69,/body\.bmcenter-bulk-modal-open\{overflow:hidden!important/);
assert.match(css70,/\.parts-v49-bulk-list\{[\s\S]*height:100%!important;[\s\S]*max-height:none!important;[\s\S]*overflow-y:auto!important/);
console.log('bulk-modal-scroll.test: OK');
