import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const phones=fs.readFileSync(new URL('../src/v102/pages/SmartphonesV102.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/v1074.css',import.meta.url),'utf8');
assert.match(main,/const\[listStatuses,setListStatuses\]=useState\(\[\]\)/,'lista de disponíveis deve iniciar aceitando todos os status');
assert.match(main,/const saleReadyStatuses=\[\.\.\.new Set\(availableInventory\.map/,'status da lista deve vir dinamicamente do estoque disponível');
assert.match(main,/onClick=\{\(\)=>setListStatuses\(\[\]\)\}>Todos<\/button>/,'lista deve oferecer filtro Todos');
assert.match(main,/const setSaleValue=v=>\{[\s\S]*receivedAmount:value/,'valor vendido deve sincronizar valor recebido');
assert.match(main,/sale-field-delivery[\s\S]*?<option>Retirada<\/option><option>Entrega local<\/option><option>Outro<\/option>/,'entrega deve ter somente Retirada, Entrega local e Outro');
assert.doesNotMatch(main,/sale-field-delivery[\s\S]{0,300}?(Correios|Envio por transportadora)/,'entrega não deve manter opções removidas');
assert.match(main,/function GlobalInlineSelectLayer\(\)/,'deve existir seletor inline global');
assert.match(main,/<CloudGate\/><GlobalInlineSelectLayer\/>/,'seletor inline global deve ser montado no app');
assert.match(main,/type==='number'&&Number\(value\|\|0\)===0[\s\S]*?currentTarget\.value=''/,'campos numéricos zerados devem limpar visualmente o zero ao focar');
assert.match(phones,/className="v10540-sort-select"/,'Smartphones deve ter campo Ordenar');
assert.match(phones,/className=\{`v10540-favorite-icon/,'Favoritos deve usar botão compacto só com ícone');
assert.match(css,/global-inline-select-menu/,'CSS deve estilizar menu de seleção inline');
assert.match(css,/v10538-list-selection\{display:flex!important;flex-direction:column/,'lista móvel deve impedir colapso/sobreposição da seleção');
console.log('mobile-sales-selects-v10540.test: OK');
