import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/v1054.css',import.meta.url),'utf8');
assert.match(main,/import'\.\/v1053\.css';import'\.\/v1054\.css';/,'v1054 deve carregar por último');
assert.match(main,/const APP_VERSION='10\.5\.4'/,'versão 10.5.4 ausente');
assert.match(css,/sale-register-modal \.sale-data-grid,[\s\S]*display:flex!important/,'venda mobile deve usar flex-wrap');
assert.match(css,/sale-field-value\{flex:0 0 88px!important;width:88px!important/,'valor vendido deve ter largura semântica');
assert.match(css,/sale-field-installments\{flex:0 0 48px!important;width:48px!important/,'parcelas deve permanecer pequeno');
assert.match(css,/purchase-data-compact\{[\s\S]*display:flex!important/,'dados da compra mobile deve usar flex-wrap');
assert.match(css,/purchase-field-date\{flex:0 0 96px!important;width:96px!important/,'data da compra deve ter largura de data');
assert.match(css,/purchase-field-paid\{flex:0 0 82px!important;width:82px!important/,'valor pago deve ser compacto');
assert.doesNotMatch(css,/purchase-data-compact>label\.v57-bank\{[^}]*grid-column:1\/-1!important/,'conta/banco não pode voltar a linha inteira');
console.log('mobile-semantic-width-v1053.test: OK');
