import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/v10486.css',import.meta.url),'utf8');
assert.match(main,/import'\.\/v10484\.css';import'\.\/v10486\.css';/,'v10486.css deve sobrepor a camada anterior');
assert.match(main,/const APP_VERSION='10\.5\.5'/,'versão 10.5.1 não encontrada');
assert.match(css,/grid-template-rows:auto auto auto auto auto!important/,'modal mobile deve usar apenas linhas automáticas');
assert.match(css,/\.parts-v84-refund-dialog>header\{top:0!important\}/,'header deve ficar fixo no topo');
assert.match(css,/\.parts-v84-refund-dialog>footer\{bottom:0!important\}/,'footer deve ficar fixo no rodapé');
assert.match(css,/\.parts-v84-refund-impact\{[\s\S]*min-height:0!important/,'painel de impacto não pode expandir com altura sobrando');
console.log('returns-financial-mobile.test: OK');
