import assert from 'node:assert/strict';
import fs from 'node:fs';
const page=fs.readFileSync(new URL('../src/v102/pages/SmartphonesV102.jsx',import.meta.url),'utf8');
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/v10478.css',import.meta.url),'utf8');
assert.match(main,/import'\.\/v10478\.css';import'\.\/v10479\.css';/,'v10479 deve ser a última camada visual');
assert.match(main,/const APP_VERSION='10\.4\.82'/,'versão 10.4.80 não encontrada');
const toolbar=page.match(/<section className="v102-toolbar v10313-main-toolbar">([\s\S]*?)<\/section>/)?.[1]||'';
assert.ok(toolbar,'toolbar de Smartphones não encontrada');
const searchAt=toolbar.indexOf('Buscar modelo ou etiqueta');
const tagAt=toolbar.indexOf('v10478-tag-filter');
const statusAt=toolbar.indexOf('v1041-status-trigger');
const favoriteAt=toolbar.indexOf('Favoritos');
const moreAt=toolbar.indexOf('Mais filtros');
assert.ok(searchAt>=0&&tagAt>searchAt&&statusAt>tagAt&&favoriteAt>statusAt&&moreAt>favoriteAt,'ordem deve ser Busca / Etiquetas / Status / Favoritos / Mais filtros');
assert.match(css,/grid-template-columns:minmax\(230px,1fr\) minmax\(175px,245px\) max-content max-content max-content/,'toolbar desktop deve ficar em uma linha');
assert.match(css,/\.v102-money,\.v102-money-editable\{[\s\S]*height:34px!important/,'faixa financeira deve ser compacta');
assert.match(css,/\.v102-inline-money\{[\s\S]*border:0!important;[\s\S]*background:transparent!important/,'valores não devem usar quadrados individuais altos');
console.log('smartphones-density.test: OK');
