import assert from 'node:assert/strict';
import fs from 'node:fs';
const page=fs.readFileSync(new URL('../src/v102/pages/SmartphonesV102.jsx',import.meta.url),'utf8');
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/v10478.css',import.meta.url),'utf8');
const latestCss=fs.readFileSync(new URL('../src/v1074.css',import.meta.url),'utf8');
assert.match(main,/import'\.\/v10478\.css';import'\.\/v10479\.css';/,'v10479 deve ser a última camada visual');
assert.match(main,/const APP_VERSION='\d+\.\d+\.\d+'/, 'APP_VERSION deve existir no código');
const toolbar=page.match(/<section className="v102-toolbar v10313-main-toolbar">([\s\S]*?)<\/section>/)?.[1]||'';
assert.ok(toolbar,'toolbar de Smartphones não encontrada');
const searchAt=toolbar.indexOf('Buscar modelo ou etiqueta');
const tagAt=toolbar.indexOf('v10478-tag-filter');
const statusAt=toolbar.indexOf('v1041-status-trigger');
const moreAt=toolbar.indexOf('Mais filtros');
const sortAt=toolbar.indexOf('v10540-sort-select');
const favoriteAt=toolbar.indexOf('v10540-favorite-icon');
assert.ok(searchAt>=0&&tagAt>searchAt&&statusAt>tagAt&&moreAt>statusAt&&sortAt>moreAt&&favoriteAt>sortAt,'ordem deve ser Busca / Etiquetas / Status / Mais filtros / Ordenar / Favoritos');
assert.match(latestCss,/grid-template-columns:minmax\(0,1fr\) minmax\(0,1fr\) 42px/,'mobile deve reservar a terceira coluna para o ícone Favoritos');
assert.match(css,/grid-template-columns:minmax\(230px,1fr\) minmax\(175px,245px\) max-content max-content max-content/,'toolbar desktop deve ficar em uma linha');
assert.match(css,/\.v102-money,\.v102-money-editable\{[\s\S]*height:34px!important/,'faixa financeira deve ser compacta');
assert.match(css,/\.v102-inline-money\{[\s\S]*border:0!important;[\s\S]*background:transparent!important/,'valores não devem usar quadrados individuais altos');
console.log('smartphones-density.test: OK');
