import assert from 'node:assert/strict';
import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.jsx',import.meta.url),'utf8');
const phonesView=fs.readFileSync(new URL('../src/v102/pages/SmartphonesV102.jsx',import.meta.url),'utf8');
const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url),'utf8'));
const parts=main.slice(main.indexOf('function Parts(){'),main.indexOf('\n\nfunction PartsInventoryPage'));
assert.match(main,/APP_VERSION='10\.4\.65'/);
assert.match(main,/OKEY='bmcenter-parts-orders'/);
assert.match(main,/phone-editor-v57/);
assert.match(main,/subtitle=\"Editar registro do aparelho\"/);
assert.match(main,/v57-device-card/);
assert.match(main,/v57-purchase-card/);
assert.match(main,/v57-middle-grid/);
assert.match(main,/v57-parts-card/);
assert.match(main,/v57-history-card/);
assert.match(main,/v57-tags-card/);
assert.match(main,/Adicionar item/);
assert.match(main,/bulkStagedOrders/);
assert.match(main,/stageCurrentBulkOrder/);
assert.match(main,/Um ou vários pedidos no mesmo lançamento/);
assert.match(main,/Salvar este e adicionar outro pedido/);
assert.match(main,/parts-v62-bulk-dialog/);
assert.match(main,/parts-v62-bulk-meta/);
assert.doesNotMatch(main,/label>Previsão<input type="date" value=\{bulkDraft\.expectedDate\}/,'Previsão deve permanecer removida do pedido em massa');
assert.match(main,/Excluir a peça \"\$\{row\.part\.name\}\" deste aparelho/);
assert.doesNotMatch(main,/parts-editor-v1053/);

assert.match(main,/effectivePartCost\(part\)/);
assert.match(parts,/Pedidos são somente de peças/);
assert.match(parts,/Confirmar tudo/);
assert.match(parts,/Receber tudo/);
assert.match(parts,/Editar pedido/);
assert.match(parts,/Excluir pedido/);
assert.match(parts,/Frete rateado/);
assert.match(parts,/Custo efetivo/);
assert.match(parts,/Pedido em massa/);
assert.match(parts,/Um ou vários pedidos no mesmo lançamento/);
assert.match(parts,/Adicionar produto/);
assert.match(parts,/Selecionar filtrados/);
assert.match(main,/bulkPhoneProductsTotal/,'cartão do aparelho deve mostrar o total somado dos produtos vinculados');
assert.match(main,/handleBulkUnitPriceTab/,'TAB no valor unitário deve avançar ou criar o próximo produto');
assert.match(main,/data-bulk-product-name/,'novo produto precisa receber foco automático no nome');
assert.match(parts,/createMultiBulkPartsOrder/);
assert.match(parts,/activeSuppliers=\[\.\.\.suppliers\]\.filter/,'fornecedores do módulo não podem ficar limitados por categoria');
assert.match(parts,/expandedOrderCards/);
assert.match(parts,/expandedQuoteRows/);
assert.match(parts,/parts-v50-order-summary/);
assert.match(parts,/parts-v50-quote-card/);
assert.match(parts,/Todas as peças/);
assert.match(parts,/Toda situação/);
assert.match(parts,/Todos os fornecedores/);
assert.doesNotMatch(parts,/bulkSelected|bulkPrices|bulkDraft\.partName|bulkDraft\.unitPrice/,'fluxo antigo de um único produto deve estar removido');
assert.doesNotMatch(parts,/blankPhone\(/,'Central de Peças não pode cadastrar aparelhos');
assert.doesNotMatch(parts,/save\(IKEY/,'Pedidos não podem dar entrada automática no estoque geral');
assert.doesNotMatch(phonesView,/setPhotoPhone|photo-shortcut|<Camera/,'Photo Studio/atalho de fotos deve permanecer removido');
for(const dependency of Object.keys({...pkg.dependencies,...pkg.devDependencies}))assert.doesNotMatch(dependency,/mediapipe|onnx|rembg|transformers/i);
console.log('source-contracts.test: OK');
