import React from 'react';
import {CheckSquare,Search} from 'lucide-react';
export default function BatchV102({rows,selected,setSelected,query,setQuery,statusFilter,setStatusFilter,statuses,newStatus,setNewStatus,newTag,setNewTag,applyBatch,toggle,allSelected,daysSince,phoneDisplayName}){
 return <div className="v102-page"><header className="v102-hero"><div><span>EDIÇÃO EM MASSA</span><h1>Ações em lote</h1><p>Selecione aparelhos e aplique alterações de forma rápida.</p></div><div className="v102-total-pill"><strong>{selected.length}</strong><span>selecionados</span></div></header>
  <section className="v102-toolbar v102-batch-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar aparelho"/></label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>Ativos</option><option>Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></section>
  <section className="v102-batch-command"><label><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?[]:rows.map(p=>p.id))}/><span>Selecionar todos</span></label><select value={newStatus} onChange={e=>setNewStatus(e.target.value)}><option value="">Status: não alterar</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><input value={newTag} onChange={e=>setNewTag(e.target.value)} placeholder="Adicionar etiqueta"/><button className="primary" disabled={!selected.length} onClick={applyBatch}><CheckSquare size={14}/> Aplicar</button></section>
  <section className="v102-batch-list">{rows.map(p=><article className={selected.includes(p.id)?'selected':''} key={p.id} onClick={()=>toggle(p.id)}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)} onClick={e=>e.stopPropagation()}/><div><b>{phoneDisplayName(p,{includeCode:false})}</b><small>{[p.color,p.storage].filter(Boolean).join(' · ')||'Sem detalhes'}</small></div><span className="v102-status-badge">{p.status}</span><em>{daysSince(p.lastActivityAt||p.date)} dias</em></article>)}</section>
 </div>
}
