import React,{useEffect,useState} from 'react';
import {Clock3,Eye,FileText,Filter,MoreHorizontal,Plus,RotateCcw,Search,Settings,Star,Trash2,WalletCards,X,TrendingUp} from 'lucide-react';
function capacity(value){const text=String(value??'').trim();if(!text)return'';return /gb$/i.test(text)?text:`${text}GB`}
function specs(phone){return [phone.color,capacity(phone.storage),phone.ram&&`${capacity(phone.ram)} RAM`,phone.nfc===true?'NFC':'',phone.connector||'',phone.screenProtector===true?'Película':'',phone.caseIncluded===true?'Capinha':'',phone.likeNew===true?'Estado de novo':'',phone.biometrics===true?'Biometria':''].filter(Boolean).join(' · ')||'Sem detalhes'}
function InlineMoney({label,value,onCommit,tone=''}){const[draft,setDraft]=useState(String(Number(value||0).toFixed(2)).replace('.',','));useEffect(()=>setDraft(String(Number(value||0).toFixed(2)).replace('.',',')),[value]);const commit=()=>{const normalized=Number(String(draft).replace(/\./g,'').replace(',','.'));if(Number.isFinite(normalized))onCommit(Math.max(0,normalized));else setDraft(String(Number(value||0).toFixed(2)).replace('.',','))};return <label className={`v102-inline-money ${tone}`}><span>{label}</span><div><small>R$</small><input inputMode="decimal" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setDraft(String(Number(value||0).toFixed(2)).replace('.',','));e.currentTarget.blur()}}}/></div></label>}

function draftDate(value){if(!value)return'Salvo anteriormente';try{return `Salvo em ${new Date(value).toLocaleString('pt-BR')}`}catch{return'Salvo anteriormente'}}
function DraftPanel({phoneDraft,batchDraft,continuePhoneDraft,continueBatchDraft,deletePhoneDraft,deleteBatchDraft}){
 const drafts=[phoneDraft&&{id:'phone',title:[phoneDraft.phone?.brand,phoneDraft.phone?.model].filter(Boolean).join(' ')||'Novo aparelho',subtitle:'Cadastro individual',savedAt:phoneDraft.savedAt,onContinue:continuePhoneDraft,onDelete:deletePhoneDraft},batchDraft&&{id:'batch',title:`Cadastro em massa · ${(batchDraft.rows||[]).filter(row=>row.brand||row.model).length||0} aparelho(s) preenchido(s)`,subtitle:'Lote de aparelhos',savedAt:batchDraft.savedAt,onContinue:continueBatchDraft,onDelete:deleteBatchDraft}].filter(Boolean);
 if(!drafts.length)return null;
 return <section className="v102-drafts-panel"><header><div><Clock3 size={16}/><div><b>Rascunhos</b><small>Continue cadastros que ainda não foram finalizados.</small></div></div><span>{drafts.length}</span></header><div className="v102-drafts-list">{drafts.map(draft=><article key={draft.id}><div className="v102-draft-icon"><Clock3 size={15}/></div><div className="v102-draft-copy"><small>{draft.subtitle}</small><b>{draft.title}</b><span>{draftDate(draft.savedAt)}</span></div><div className="v102-draft-actions"><button className="continue" onClick={draft.onContinue}>Continuar cadastro</button><button className="delete" title="Excluir rascunho" onClick={draft.onDelete}><Trash2 size={14}/></button></div></article>)}</div></section>
}

function BinaryFilter({label,value,onChange}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="Todos">Todos</option><option value="Sim">Sim</option><option value="Não">Não</option></select></label>}

export default function SmartphonesV102({filtered,statuses,statusFilter,setStatusFilter,allTags,tagFilter,setTagFilter,query,setQuery,onlyFavorites,setOnlyFavorites,profiles,showProductCode,phoneTotalCost,money,toggleFavorite,changeStatus,setDetail,setEdit,setColumnEditor,setBatchCreate,blankPhone,items,actionPhone,setActionPhone,setSalePhone,persist,updateFinancial,totalExpected,phoneDraft,batchDraft,continuePhoneDraft,continueBatchDraft,deletePhoneDraft,deleteBatchDraft}){
 const[showExtraFilters,setShowExtraFilters]=useState(false);
 const[extra,setExtra]=useState({ram:'Todos',storage:'Todos',connector:'Todos',nfc:'Todos',biometrics:'Todos',likeNew:'Todos',screenProtector:'Todos',caseIncluded:'Todos'});
 const uniqueValues=key=>[...new Set(items.map(phone=>String(phone?.[key]??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true,sensitivity:'base'}));
 const ramOptions=uniqueValues('ram'),storageOptions=uniqueValues('storage'),connectorOptions=uniqueValues('connector');
 const booleanMatch=(phone,key,value)=>value==='Todos'||(value==='Sim'?phone?.[key]===true:phone?.[key]===false);
 const advancedFiltered=filtered.filter(phone=>
  (extra.ram==='Todos'||String(phone.ram??'').trim()===extra.ram)&&
  (extra.storage==='Todos'||String(phone.storage??'').trim()===extra.storage)&&
  (extra.connector==='Todos'||String(phone.connector??'').trim()===extra.connector)&&
  booleanMatch(phone,'nfc',extra.nfc)&&
  booleanMatch(phone,'biometrics',extra.biometrics)&&
  booleanMatch(phone,'likeNew',extra.likeNew)&&
  booleanMatch(phone,'screenProtector',extra.screenProtector)&&
  booleanMatch(phone,'caseIncluded',extra.caseIncluded)
 );
 const activeExtraCount=Object.values(extra).filter(value=>value!=='Todos').length;
 const setExtraFilter=(key,value)=>setExtra(current=>({...current,[key]:value}));
 const clearExtraFilters=()=>setExtra({ram:'Todos',storage:'Todos',connector:'Todos',nfc:'Todos',biometrics:'Todos',likeNew:'Todos',screenProtector:'Todos',caseIncluded:'Todos'});
 return <div className="v102-page"><header className="v102-hero v102-smartphones-hero"><div><span>INVENTÁRIO</span><div className="v102-title-line"><h1>Smartphones</h1><div className="v102-receivable"><TrendingUp size={16}/><div><small>Previsão ao vender o estoque</small><strong>{money(totalExpected)}</strong></div></div></div><p>{advancedFiltered.length} aparelho(s) nesta visão.</p></div><div className="v102-page-actions"><button onClick={()=>setColumnEditor(true)}><Settings size={15}/> Exibição</button><button className="v102-draft-aware-button" onClick={()=>setBatchCreate(true)}><Plus size={15}/> Em massa{batchDraft&&<span className="v102-draft-dot">1</span>}</button><button className="primary v102-draft-aware-button" onClick={()=>setEdit(blankPhone(items.length+1))}><Plus size={15}/> Novo aparelho{phoneDraft&&<span className="v102-draft-dot light">1</span>}</button></div></header>
<DraftPanel phoneDraft={phoneDraft} batchDraft={batchDraft} continuePhoneDraft={continuePhoneDraft} continueBatchDraft={continueBatchDraft} deletePhoneDraft={deletePhoneDraft} deleteBatchDraft={deleteBatchDraft}/>
<section className="v102-toolbar v10313-main-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar modelo ou etiqueta"/></label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="Todos">Todos os status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option value="Todas">Todas as etiquetas</option>{allTags.map(t=><option key={t}>{t}</option>)}</select><button className={onlyFavorites?'active':''} onClick={()=>setOnlyFavorites(v=>!v)}><Star size={14}/> Favoritos</button><button className={`v10313-more-filters ${showExtraFilters||activeExtraCount?'active':''}`} onClick={()=>setShowExtraFilters(value=>!value)}><Filter size={14}/> Mais filtros{activeExtraCount>0&&<span>{activeExtraCount}</span>}</button></section>
{showExtraFilters&&<section className="v10313-extra-filters">
 <div className="v10313-filter-fields">
  <label><span>RAM</span><select value={extra.ram} onChange={e=>setExtraFilter('ram',e.target.value)}><option value="Todos">Todas</option>{ramOptions.map(value=><option value={value} key={value}>{capacity(value)} RAM</option>)}</select></label>
  <label><span>Armazenamento</span><select value={extra.storage} onChange={e=>setExtraFilter('storage',e.target.value)}><option value="Todos">Todos</option>{storageOptions.map(value=><option value={value} key={value}>{capacity(value)}</option>)}</select></label>
  <label><span>Conector</span><select value={extra.connector} onChange={e=>setExtraFilter('connector',e.target.value)}><option value="Todos">Todos</option>{connectorOptions.map(value=><option value={value} key={value}>{value}</option>)}</select></label>
  <BinaryFilter label="NFC" value={extra.nfc} onChange={value=>setExtraFilter('nfc',value)}/>
  <BinaryFilter label="Biometria" value={extra.biometrics} onChange={value=>setExtraFilter('biometrics',value)}/>
  <BinaryFilter label="Estado de novo" value={extra.likeNew} onChange={value=>setExtraFilter('likeNew',value)}/>
  <BinaryFilter label="Película" value={extra.screenProtector} onChange={value=>setExtraFilter('screenProtector',value)}/>
  <BinaryFilter label="Capinha" value={extra.caseIncluded} onChange={value=>setExtraFilter('caseIncluded',value)}/>
 </div>
 <div className="v10313-filter-footer"><small>{activeExtraCount?`${activeExtraCount} filtro(s) adicional(is) ativo(s)`:'Nenhum filtro adicional ativo'}</small>{activeExtraCount>0&&<button onClick={clearExtraFilters}><RotateCcw size={13}/> Limpar</button>}</div>
</section>}
<section className="v102-device-list">{advancedFiltered.map(x=>{const cost=phoneTotalCost(x),profit=Number(x.expected||0)-cost;const published=profiles.filter(profile=>(x.ads||[]).some(ad=>ad?.publications?.[profile.id]?.status==='published')).length;return <article key={x.id} className="v102-device-row"><button className={`v102-star ${x.favorite?'active':''}`} onClick={()=>toggleFavorite(x)}><Star size={14}/></button><div className="v102-device-name"><h3>{x.brand} {x.model}</h3><p>{specs(x)}</p>{showProductCode()&&x.code&&<small>{x.code}</small>}</div><div className="v102-status"><select value={x.status} onChange={e=>changeStatus(x.id,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><small>{published?`${published} perfil(is) publicado(s)`:'Sem anúncio'}</small></div><div className="v102-money v102-money-editable"><InlineMoney label="Custo" value={cost} onCommit={v=>updateFinancial(x.id,'cost',v)}/><InlineMoney label="Valor de venda" value={x.expected} onCommit={v=>updateFinancial(x.id,'expected',v)}/><InlineMoney label="Lucro" value={profit} tone={profit>=0?'good':'bad'} onCommit={v=>updateFinancial(x.id,'profit',v)}/></div><div className="v102-row-actions"><button onClick={()=>setDetail(x)} title="Abrir"><Eye size={15}/></button><button onClick={()=>setEdit(x)} title="Editar"><FileText size={15}/></button><div className="v102-menu-anchor"><button onClick={()=>setActionPhone(cur=>cur?.phone?.id===x.id?null:{phone:x})}><MoreHorizontal size={16}/></button>{actionPhone?.phone?.id===x.id&&<div className="v102-context"><button onClick={()=>{setSalePhone(x);setActionPhone(null)}}><WalletCards size={15}/> Registrar venda</button><button className="danger" onClick={()=>{if(confirm('Excluir aparelho?'))persist(items.filter(i=>i.id!==x.id));setActionPhone(null)}}><X size={15}/> Excluir</button></div>}</div></div></article>})}</section></div>}
